# These configs are mostly for laptops. This is addemdum to Keybinds.conf

$mainMod = SUPER
$scriptsDir = $HOME/.config/hypr/scripts
$UserConfigs = $HOME/.config/hypr/user-config

binde = , xf86KbdBrightnessDown, exec, $scriptsDir/brightness-kbd.sh --dec # decrease keyboard brightness
binde = , xf86KbdBrightnessUp, exec, $scriptsDir/brightness-kbd.sh --inc # increase keyboard brightness
binde = , xf86MonBrightnessDown, exec, $scriptsDir/brightness.sh --dec # decrease monitor brightness
binde = , xf86MonBrightnessUp, exec, $scriptsDir/brightness.sh --inc # increase monitor brightness

# Screenshot keybindings using F6 (no PrinSrc button)
bind = $mainMod, F6, exec, $HOME/.local/bin/hyprshot -m window  # screenshot
bind = $mainMod SHIFT, S, exec, $HOME/.local/bin/hyprshot -m region # screenshot (area)
bind = $mainMod CTRL, F6, exec, $HOME/.local/bin/hyprshot -m window -D 5 # screenshot (5 secs delay)
bind = $mainMod ALT, F6, exec,  $HOME/.local/bin/hyprshot -m window -D 10 # screenshot (10 secs delay)
bind = ALT, F6, exec, $HOME/.local/bin/hyprshot -m window -m active # screenshot (active window only)

bindl = , switch:on:Lid Switch,exec,echo "monitor = eDP-1, disable" > $UserConfigs/laptop-display.conf
